// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dpl.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dpl.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace dpl {

namespace {

const ::google::protobuf::Descriptor* FullyConnected_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FullyConnected_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_dpl_2eproto() {
  protobuf_AddDesc_dpl_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "dpl.proto");
  GOOGLE_CHECK(file != NULL);
  FullyConnected_descriptor_ = file->message_type(0);
  static const int FullyConnected_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FullyConnected, numoutputneurons_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FullyConnected, name_),
  };
  FullyConnected_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FullyConnected_descriptor_,
      FullyConnected::default_instance_,
      FullyConnected_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FullyConnected, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FullyConnected, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FullyConnected));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_dpl_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FullyConnected_descriptor_, &FullyConnected::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_dpl_2eproto() {
  delete FullyConnected::default_instance_;
  delete FullyConnected_reflection_;
}

void protobuf_AddDesc_dpl_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tdpl.proto\022\003dpl\"8\n\016FullyConnected\022\030\n\020nu"
    "mOutputNeurons\030\001 \002(\005\022\014\n\004name\030\002 \001(\t", 74);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dpl.proto", &protobuf_RegisterTypes);
  FullyConnected::default_instance_ = new FullyConnected();
  FullyConnected::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_dpl_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_dpl_2eproto {
  StaticDescriptorInitializer_dpl_2eproto() {
    protobuf_AddDesc_dpl_2eproto();
  }
} static_descriptor_initializer_dpl_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int FullyConnected::kNumOutputNeuronsFieldNumber;
const int FullyConnected::kNameFieldNumber;
#endif  // !_MSC_VER

FullyConnected::FullyConnected()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dpl.FullyConnected)
}

void FullyConnected::InitAsDefaultInstance() {
}

FullyConnected::FullyConnected(const FullyConnected& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dpl.FullyConnected)
}

void FullyConnected::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  numoutputneurons_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FullyConnected::~FullyConnected() {
  // @@protoc_insertion_point(destructor:dpl.FullyConnected)
  SharedDtor();
}

void FullyConnected::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void FullyConnected::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FullyConnected::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FullyConnected_descriptor_;
}

const FullyConnected& FullyConnected::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dpl_2eproto();
  return *default_instance_;
}

FullyConnected* FullyConnected::default_instance_ = NULL;

FullyConnected* FullyConnected::New() const {
  return new FullyConnected;
}

void FullyConnected::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    numoutputneurons_ = 0;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FullyConnected::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dpl.FullyConnected)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 numOutputNeurons = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &numoutputneurons_)));
          set_has_numoutputneurons();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // optional string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dpl.FullyConnected)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dpl.FullyConnected)
  return false;
#undef DO_
}

void FullyConnected::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dpl.FullyConnected)
  // required int32 numOutputNeurons = 1;
  if (has_numoutputneurons()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->numoutputneurons(), output);
  }

  // optional string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dpl.FullyConnected)
}

::google::protobuf::uint8* FullyConnected::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dpl.FullyConnected)
  // required int32 numOutputNeurons = 1;
  if (has_numoutputneurons()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->numoutputneurons(), target);
  }

  // optional string name = 2;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dpl.FullyConnected)
  return target;
}

int FullyConnected::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 numOutputNeurons = 1;
    if (has_numoutputneurons()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->numoutputneurons());
    }

    // optional string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FullyConnected::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FullyConnected* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FullyConnected*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FullyConnected::MergeFrom(const FullyConnected& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_numoutputneurons()) {
      set_numoutputneurons(from.numoutputneurons());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FullyConnected::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FullyConnected::CopyFrom(const FullyConnected& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FullyConnected::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void FullyConnected::Swap(FullyConnected* other) {
  if (other != this) {
    std::swap(numoutputneurons_, other->numoutputneurons_);
    std::swap(name_, other->name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FullyConnected::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FullyConnected_descriptor_;
  metadata.reflection = FullyConnected_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dpl

// @@protoc_insertion_point(global_scope)
